// <auto-generated />
using System;
using Apirestaurant.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apirestaurant.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    [Migration("20240705171419_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apirestaurant.Models.ModelsRestaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Costopedido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Detallespedidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fechapedido")
                        .HasColumnType("date");

                    b.Property<string>("Full_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numeropedido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModelsRestaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
